ui <- fluidPage(
  
  ## Butun dagilimlar icin sirayla numerik girisleri ekledik. Plot output ile daha sonra serverda istedigimiz grafikleri olusturmak uzere isimlendirme yaptık. br() fonksiyonu alttaki girislerle ustteki girislerin arasında bosluk birakmamızı saglar.
  ## Normal Distribution
 
  titlePanel("NORMAL DAGILIM"),
  numericInput(inputId = "size_norm",
               label = "Orneklem Genisligi (Normal Dagilim)",
               value = 25),
  numericInput(inputId = "mean_norm",
               label = "Ortalama",
               value = 0),
  numericInput(inputId = "sd_norm",
               label = "Standart Sapma",
               value = 1),
  plotOutput("hist_norm"),
  plotOutput("box_norm"),
  plotOutput("violin_norm"),
  plotOutput("dot_norm"),
  verbatimTextOutput("summary_norm"),
  br(),
  br(),
  
  # Uniform Distribution
  titlePanel("TEKDUZE DAGILIM"),
  numericInput(inputId = "size_unif",
               label = "Orneklem Genisligi (Tekduze Dagilim)",
               value = 25),
  numericInput(inputId = "min_unif",
               label = "Minimum",
               value = 0),
  numericInput(inputId = "max_unif",
               label = "Maximum",
               value = 1),
  plotOutput("hist_unif"),
  plotOutput("box_unif"),
  plotOutput("violin_unif"),
  plotOutput("dot_unif"),
  verbatimTextOutput("summary_unif"),
  br(),
  br(),
  
  ## T Distribution
  titlePanel("T DAGILIMI"),
  numericInput(inputId = "size_t",
               label = "Orneklem Genisligi (T Dagilimi)",
               value = 25),
  numericInput(inputId = "df_t",
               label = "Serbestlik Derecesi",
               value = 5),
  plotOutput("hist_t"),
  plotOutput("box_t"),
  plotOutput("violin_t"),
  plotOutput("dot_t"),
  verbatimTextOutput("summary_t"),
  br(),
  br(),
  
  ## F Distribution
  numericInput(inputId = "size_f",
               label = "Orneklem Genisligi (F Dagilimi)",
               value = 25),
  numericInput(inputId = "df_f_1",
               label = "Serbestlik Derecesi 1",
               value = 5),
  numericInput(inputId = "df_f_2",
               label = "Serbestlik Derecesi 2",
               value = 5),
  plotOutput("hist_f"),
  plotOutput("box_f"),
  plotOutput("violin_f"),
  plotOutput("dot_f"),
  verbatimTextOutput("summary_f"),
  br(),
  br(),
  
  ## Gamma Distribution
  numericInput(inputId = "size_gamma",
               label = "Orneklem Genisligi (Gamma Dagilimi)",
               value = 25),
  numericInput(inputId = "shape_gamma",
               label = "Sekil",
               value = 1),
  numericInput(inputId = "rate_gamma",
               label = "Oran",
               value = 1),
  plotOutput("hist_gamma"),
  plotOutput("box_gamma"),
  plotOutput("violin_gamma"),
  plotOutput("dot_gamma"),
  verbatimTextOutput("summary_gamma"),
  br(),
  br(),
  
  ## Exponential Distribution
  numericInput(inputId = "size_exp",
               label = "Orneklem Genisligi (Ustel Dagilimi)",
               value = 25),
  numericInput(inputId = "rate_exp",
               label = "Oran",
               value = 1),
  plotOutput("hist_exp"),
  plotOutput("box_exp"),
  plotOutput("violin_exp"),
  plotOutput("dot_exp"),
  verbatimTextOutput("summary_exp"),
  br(),
  br(),
  
  ## Chi - Square Distribution
  numericInput(inputId = "size_chi",
               label = "Orneklem Genisligi (Ki - Kare Dagilimi)",
               value = 25),
  numericInput(inputId = "df_chi",
               label = "Serbestlik Derecesi",
               value = 5),
  plotOutput("hist_chi"),
  plotOutput("box_chi"),
  plotOutput("violin_chi"),
  plotOutput("dot_chi"),
  verbatimTextOutput("summary_chi"),
  br(),
  br(),
  
  ## Log Normal Distribution
  numericInput(inputId = "size_log",
               label = "Orneklem Genisligi (Log Normal Dagilimi)",
               value = 25),
  numericInput(inputId = "mean_log",
               label = "Logaritmik Ortalama",
               value = 0),
  numericInput(inputId = "sd_log",
               label = "Logaritmik Standart Sapma",
               value = 1),
  plotOutput("hist_log"),
  plotOutput("box_log"),
  plotOutput("violin_log"),
  plotOutput("dot_log"),
  verbatimTextOutput("summary_log"),
  br(),
  br(),
  
  ## Beta Distribution
  numericInput(inputId = "size_beta",
               label = "Orneklem Genisligi (Beta Dagilimi)",
               value = 25),
  numericInput(inputId = "shape_beta_1",
               label = "Sekil 1",
               value = 1),
  numericInput(inputId = "shape_beta_2",
               label = "Sekil 2",
               value = 1),
  plotOutput("hist_beta"),
  plotOutput("box_beta"),
  plotOutput("violin_beta"),
  plotOutput("dot_beta"),
  verbatimTextOutput("summary_beta"),
  br(),
  br(),
  
  ## Cauchy Distribution
  numericInput(inputId = "size_cauchy",
               label = "Orneklem Genisligi (Cauchy Dagilimi)",
               value = 25),
  numericInput(inputId = "location_cauchy",
               label = "Konum",
               value = 0),
  numericInput(inputId = "scale_cauchy",
               label = "Olcek",
               value = 1),
  plotOutput("hist_cauchy"),
  plotOutput("box_cauchy"),
  plotOutput("violin_cauchy"),
  plotOutput("dot_cauchy"),
  verbatimTextOutput("summary_cauchy"),
  br(),
  br(),
  
  ## Weibull Distribution
  numericInput(inputId = "size_weibull",
               label = "Orneklem Genisligi (Weibull Dagilimi)",
               value = 25),
  numericInput(inputId = "shape_weibull",
               label = "Sekil",
               value = 1),
  numericInput(inputId = "scale_weibull",
               label = "Olcek",
               value = 1),
  plotOutput("hist_weibull"),
  plotOutput("box_weibull"),
  plotOutput("violin_weibull"),
  plotOutput("dot_weibull"),
  verbatimTextOutput("summary_weibull"),
  br(),
  br(),
)
